# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../qt_gui/PowerMonitor/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(708, 786)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.frmLeft = QtWidgets.QFrame(self.splitter)
        self.frmLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmLeft.setObjectName("frmLeft")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frmLeft)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.grpConnection = QtWidgets.QGroupBox(self.frmLeft)
        self.grpConnection.setObjectName("grpConnection")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.grpConnection)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridConnectionLayout = QtWidgets.QGridLayout()
        self.gridConnectionLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridConnectionLayout.setContentsMargins(11, 11, 11, 11)
        self.gridConnectionLayout.setSpacing(6)
        self.gridConnectionLayout.setObjectName("gridConnectionLayout")
        self.lblComPort = QtWidgets.QLabel(self.grpConnection)
        self.lblComPort.setObjectName("lblComPort")
        self.gridConnectionLayout.addWidget(self.lblComPort, 0, 0, 1, 1)
        self.frmStart = QtWidgets.QFrame(self.grpConnection)
        self.frmStart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmStart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmStart.setObjectName("frmStart")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frmStart)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnStartStop = QtWidgets.QPushButton(self.frmStart)
        self.btnStartStop.setEnabled(False)
        self.btnStartStop.setObjectName("btnStartStop")
        self.horizontalLayout.addWidget(self.btnStartStop)
        self.gridConnectionLayout.addWidget(self.frmStart, 1, 1, 1, 1)
        self.frmComPorts = QtWidgets.QFrame(self.grpConnection)
        self.frmComPorts.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmComPorts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmComPorts.setObjectName("frmComPorts")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmComPorts)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cmbComPort = QtWidgets.QComboBox(self.frmComPorts)
        self.cmbComPort.setObjectName("cmbComPort")
        self.horizontalLayout_2.addWidget(self.cmbComPort)
        self.btnComReload = QtWidgets.QPushButton(self.frmComPorts)
        self.btnComReload.setObjectName("btnComReload")
        self.horizontalLayout_2.addWidget(self.btnComReload)
        self.horizontalLayout_2.setStretch(0, 1)
        self.gridConnectionLayout.addWidget(self.frmComPorts, 0, 1, 1, 1)
        self.btnConnect = QtWidgets.QPushButton(self.grpConnection)
        self.btnConnect.setObjectName("btnConnect")
        self.gridConnectionLayout.addWidget(self.btnConnect, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridConnectionLayout)
        self.verticalLayout_4.addWidget(self.grpConnection)
        self.grpLimit = QtWidgets.QGroupBox(self.frmLeft)
        self.grpLimit.setObjectName("grpLimit")
        self.formLayout_2 = QtWidgets.QFormLayout(self.grpLimit)
        self.formLayout_2.setContentsMargins(11, 11, 11, 11)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.chkLimitMaxPointsToDisplay = QtWidgets.QCheckBox(self.grpLimit)
        self.chkLimitMaxPointsToDisplay.setChecked(True)
        self.chkLimitMaxPointsToDisplay.setObjectName("chkLimitMaxPointsToDisplay")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.chkLimitMaxPointsToDisplay)
        self.label = QtWidgets.QLabel(self.grpLimit)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtMaxPointsToDisplay = QtWidgets.QLineEdit(self.grpLimit)
        self.txtMaxPointsToDisplay.setObjectName("txtMaxPointsToDisplay")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtMaxPointsToDisplay)
        self.chkLimitMaxPointsToStore = QtWidgets.QCheckBox(self.grpLimit)
        self.chkLimitMaxPointsToStore.setObjectName("chkLimitMaxPointsToStore")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.chkLimitMaxPointsToStore)
        self.lblMaxPointsToStore = QtWidgets.QLabel(self.grpLimit)
        self.lblMaxPointsToStore.setObjectName("lblMaxPointsToStore")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblMaxPointsToStore)
        self.txtMaxPointsToStore = QtWidgets.QLineEdit(self.grpLimit)
        self.txtMaxPointsToStore.setObjectName("txtMaxPointsToStore")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtMaxPointsToStore)
        self.chkAlwaysScrollToRight = QtWidgets.QCheckBox(self.grpLimit)
        self.chkAlwaysScrollToRight.setChecked(True)
        self.chkAlwaysScrollToRight.setObjectName("chkAlwaysScrollToRight")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.chkAlwaysScrollToRight)
        self.verticalLayout_4.addWidget(self.grpLimit)
        self.grpAxis = QtWidgets.QGroupBox(self.frmLeft)
        self.grpAxis.setObjectName("grpAxis")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.grpAxis)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.chkLinkXAxis = QtWidgets.QCheckBox(self.grpAxis)
        self.chkLinkXAxis.setObjectName("chkLinkXAxis")
        self.verticalLayout_7.addWidget(self.chkLinkXAxis)
        self.btnResetYAxis = QtWidgets.QPushButton(self.grpAxis)
        self.btnResetYAxis.setObjectName("btnResetYAxis")
        self.verticalLayout_7.addWidget(self.btnResetYAxis)
        self.btnResetXAxis = QtWidgets.QPushButton(self.grpAxis)
        self.btnResetXAxis.setObjectName("btnResetXAxis")
        self.verticalLayout_7.addWidget(self.btnResetXAxis)
        self.verticalLayout_4.addWidget(self.grpAxis)
        self.grpFile = QtWidgets.QGroupBox(self.frmLeft)
        self.grpFile.setObjectName("grpFile")
        self.gridLayout = QtWidgets.QGridLayout(self.grpFile)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.txtSaveToFileName = QtWidgets.QLineEdit(self.grpFile)
        self.txtSaveToFileName.setReadOnly(True)
        self.txtSaveToFileName.setObjectName("txtSaveToFileName")
        self.gridLayout.addWidget(self.txtSaveToFileName, 1, 1, 1, 1)
        self.lblFilename = QtWidgets.QLabel(self.grpFile)
        self.lblFilename.setObjectName("lblFilename")
        self.gridLayout.addWidget(self.lblFilename, 1, 0, 1, 1)
        self.chkSaveToFile = QtWidgets.QCheckBox(self.grpFile)
        self.chkSaveToFile.setObjectName("chkSaveToFile")
        self.gridLayout.addWidget(self.chkSaveToFile, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.grpFile)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btnChooseFile = QtWidgets.QPushButton(self.frame)
        self.btnChooseFile.setObjectName("btnChooseFile")
        self.horizontalLayout_3.addWidget(self.btnChooseFile)
        self.gridLayout.addWidget(self.frame, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.grpFile)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.frmRight = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmRight.sizePolicy().hasHeightForWidth())
        self.frmRight.setSizePolicy(sizePolicy)
        self.frmRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmRight.setObjectName("frmRight")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frmRight)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plotBV = PlotWidget(self.frmRight)
        self.plotBV.setObjectName("plotBV")
        self.verticalLayout_2.addWidget(self.plotBV)
        self.plotCA = PlotWidget(self.frmRight)
        self.plotCA.setObjectName("plotCA")
        self.verticalLayout_2.addWidget(self.plotCA)
        self.plotPO = PlotWidget(self.frmRight)
        self.plotPO.setObjectName("plotPO")
        self.verticalLayout_2.addWidget(self.plotPO)
        self.plotConsumption = PlotWidget(self.frmRight)
        self.plotConsumption.setObjectName("plotConsumption")
        self.verticalLayout_2.addWidget(self.plotConsumption)
        self.plotConsumptionMean = PlotWidget(self.frmRight)
        self.plotConsumptionMean.setObjectName("plotConsumptionMean")
        self.verticalLayout_2.addWidget(self.plotConsumptionMean)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 708, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuPlots = QtWidgets.QMenu(self.menuBar)
        self.menuPlots.setObjectName("menuPlots")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionBus_voltage = QtWidgets.QAction(MainWindow)
        self.actionBus_voltage.setCheckable(True)
        self.actionBus_voltage.setChecked(True)
        self.actionBus_voltage.setObjectName("actionBus_voltage")
        self.actionCurrent = QtWidgets.QAction(MainWindow)
        self.actionCurrent.setCheckable(True)
        self.actionCurrent.setChecked(True)
        self.actionCurrent.setObjectName("actionCurrent")
        self.actionPower = QtWidgets.QAction(MainWindow)
        self.actionPower.setCheckable(True)
        self.actionPower.setChecked(True)
        self.actionPower.setObjectName("actionPower")
        self.actionConsumption = QtWidgets.QAction(MainWindow)
        self.actionConsumption.setCheckable(True)
        self.actionConsumption.setChecked(True)
        self.actionConsumption.setObjectName("actionConsumption")
        self.actionMean_consumption = QtWidgets.QAction(MainWindow)
        self.actionMean_consumption.setCheckable(True)
        self.actionMean_consumption.setChecked(True)
        self.actionMean_consumption.setObjectName("actionMean_consumption")
        self.menuPlots.addAction(self.actionBus_voltage)
        self.menuPlots.addAction(self.actionCurrent)
        self.menuPlots.addAction(self.actionPower)
        self.menuPlots.addAction(self.actionConsumption)
        self.menuPlots.addAction(self.actionMean_consumption)
        self.menuBar.addAction(self.menuPlots.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Power Monitor 0.1"))
        self.grpConnection.setTitle(_translate("MainWindow", "Connection"))
        self.lblComPort.setText(_translate("MainWindow", "COM Port"))
        self.btnStartStop.setText(_translate("MainWindow", "Start"))
        self.btnComReload.setText(_translate("MainWindow", "Reload"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.grpLimit.setTitle(_translate("MainWindow", "Data display"))
        self.chkLimitMaxPointsToDisplay.setText(_translate("MainWindow", "Limit max points to display"))
        self.label.setText(_translate("MainWindow", "Max points to display"))
        self.chkLimitMaxPointsToStore.setText(_translate("MainWindow", "Limit max points to store"))
        self.lblMaxPointsToStore.setText(_translate("MainWindow", "Max points to store"))
        self.chkAlwaysScrollToRight.setText(_translate("MainWindow", "Always scroll to newest"))
        self.grpAxis.setTitle(_translate("MainWindow", "Axis"))
        self.chkLinkXAxis.setText(_translate("MainWindow", "Link X-axis"))
        self.btnResetYAxis.setText(_translate("MainWindow", "Reset Y Axis"))
        self.btnResetXAxis.setText(_translate("MainWindow", "Reset X Axis"))
        self.grpFile.setTitle(_translate("MainWindow", "Export to file"))
        self.lblFilename.setText(_translate("MainWindow", "File"))
        self.chkSaveToFile.setText(_translate("MainWindow", "Save to file"))
        self.btnChooseFile.setText(_translate("MainWindow", "Choose file"))
        self.menuPlots.setTitle(_translate("MainWindow", "Plots"))
        self.actionBus_voltage.setText(_translate("MainWindow", "Bus voltage"))
        self.actionCurrent.setText(_translate("MainWindow", "Current"))
        self.actionPower.setText(_translate("MainWindow", "Power"))
        self.actionConsumption.setText(_translate("MainWindow", "Consumption"))
        self.actionMean_consumption.setText(_translate("MainWindow", "Mean consumption"))

